
general.import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]
# $HOME/.config/alacritty/alacritty.toml
# by Rito Ghosh 2023-10-06

# Alacritty now uses TOML formatting for its config files.
# This is a simple example.

# There are the specification here: https://github.com/alacritty/alacritty/blob/master/extra/man/alacritty.5.scd
# It is not obvious how it translates to TOML. But it is extremely straightforward.

# example: WINDOW, COLORS, etc. are tables, and should be represented as [window], [colors], respectively.
# specifics of variables go under them. e.g.- look under "dynamic_padding" under-
# https://github.com/alacritty/alacritty/blob/master/extra/man/alacritty.5.scd#window
# write `dynamic_padding = true` (without backticks -`) under the table [window]
# for variables with multiple values, use "dotted keys". Like setting `padding.x = 5` under [window].
# This is simple. If not clear, do several trials and errors.

# Below is my initial set-up. The TOML homepage (https://toml.io/en/v1.0.0) was very helpful in figuring this out. 
# I put the file alacritty.toml in $HOME/.config/alacritty. However it can be kept anywhere among the places mentioned in
# https://github.com/alacritty/alacritty/tree/master#configuration

general.live_config_reload = true

[env]

TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1.0"

[window]

dimensions.columns = 110
dimensions.lines = 53

position.x = 150
position.y = 20

opacity = 0.75

startup_mode = "Windowed"

decorations = "Full"
decorations_theme_variant = "Dark"

level = "Normal"

[cursor]

style.shape = "Beam"

vi_mode_style.shape = "Block"
vi_mode_style.blinking = "On"
blink_interval = 300

[terminal]

osc52 = "OnlyCopy"

[font]
    size = 12.0

    [font.normal]
        family = "FiraCode Nerd Font Mono"
        style  = "Regular"

    [font.bold]
        family = "FiraCode Nerd Font Mono"
        style  = "Bold"

    [font.bold_italic]
        family = "FiraCode Nerd Font Mono"
        style  = "Bold Italic"

    [font.glyph_offset]
        x = 0
        y = 0

    [font.italic]
        family = "FiraCode Nerd Font Mono"
        style  = "Italic"

    [font.offset]
        x = 0
        y = 0

[scrolling]
    history    = 10000
    multiplier = 3

[[hints.enabled]]
	regex = "[^ ]+\\.rs:\\d+:\\d+"
	command = { program = "code", args = [ "--goto" ] }
	mouse = { enabled = true }

# Tip: for inspiration, look for values in the source code files of your favorite VS Code themes, and use the color picker in
# Google to test colors before setting a value, or simply using an editor such as VS Code where colors are displayed in a 
# small box when a HEX is detected by the editor.
